### PR TITLE
Adapt and reuse more of AB4's Automated Tests and do some spelling & cleanup.

### LINKED ISSUE #65: Add tests for `ViewCommand`

### LINKED ISSUE #78: Add home command testing
Requires testing of UI. We have yet to figure that out

### LINKED ISSUE #121: Outstanding tasks in testing
- [ ] #74 
- [x] #78 
- [x] #65 
- [x] #124
- [x] #130

### LINKED ISSUE #130: Add bare bones testing for all possible javafx components to ensure they are mountable.

### LINKED ISSUE #133: Add attribution for use of AB4 automated tests
> If you use code from AB4, it is better to acknowledge. But no need to acknowledge AB3.

_Originally posted by @damithc in https://github.com/nus-cs2103-AY2122S1/forum/issues/321#issuecomment-944846057_

Referring to #132

### PR DESCRIPTION
**Pull request by bharathcs**
Continuation of #132 . These two PRs will be the only use of adapted AB4 code to work on automated gui testing

Fixes #78, Fixes #75, Fixes #65, Fixes #133, Fixes #130, Fixes #121

### CODE REVIEW

**Review by sheehui — CHANGES_REQUESTED** [review]
Wow i'm so impressed with this!! GUI testing is not easy. Good job for thinking about using AB4. In the meantime, we should give credit to AB4 and acknowledge their work. Please write comments in the files where you have adapted AB4 code that we have referenced them as instructed by cs2103t tp requirements.

**Comment by bharathcs** [comment]
Latest commit adds attribution, Fixes #133

**Comment by bharathcs** [comment]
> Wow i'm so impressed with this!! GUI testing is not easy. Good job for thinking about using AB4. In the meantime, we should give credit to AB4 and acknowledge their work. Please write comments in the files where you have adapted AB4 code that we have referenced them as instructed by cs2103t tp requirements.

Thanks @sheehui, and I've just done up the attribution :)

**Review by sheehui — APPROVED** [review]
right thanks. Make sure that code reuse acknowledgement for PR #132 is also updated and you are good to go. Plus, I really like the proper use of `assertEquals`, `assertNotEquals`, `assertTrue`, `assertFalse`. Thanks for correcting tc's typos :)

**Pull request merged**
