### PR TITLE
Have Model update Storage directly and remove Logic-Storage connection.

### PR DESCRIPTION
**Pull request by bharathcs**
In line with tc's grand layered cake, we need to cut the Logic-Storage connection and have any updates to storage be propagated through model properly.

## Checklist

- [x] Have you ensured [`./src/test`](./src/test) is up to date?
- [x] Have you added javadocs?
- [x] Have you updated User Guide / Dev Guide in [`./docs/`](./docs)?
  - [x] Do up Storage diagrams : @sheehui (not needed)
  - [x] Do up model, logic diagrams : @bharathcs 
  - [x] /docs/ need to update some of the text on Model: Donny
- [x] Handle new changes after the current PR by tee chin / mrinal gets cleared.

[If any of the above steps are not complete, please make a draft PR instead]

### CODE REVIEW

**Comment by bharathcs** [comment]
Fixes #6

**Comment by bharathcs** [comment]
# :warning: Wait for #20 to merge before merging this
There are `new ModelManager()` calls in that PR that will not fly with the changes I am making in this PR).

**Review by DonnyS57 — APPROVED** [review]
LGTM! I'm just wondering if the changes to the test files will be permanent or are the nulls just placeholder values for now?

**Review by Bluntsord — COMMENTED** [review]
very nice. great success

**Comment by bharathcs** [comment]
> LGTM! I'm just wondering if the changes to the test files will be permanent or are the nulls just placeholder values for now?

Right right so basically Model used to not know what storage was, because in most scenarios there is no interaction with storage. Only the `saveAddressBook()` function requires use of storage. The null is passed for storage in creating Model many times in the test suite because those tests only check for Model functioning internally, and it isn't testing for its ability to save to storage. Does that clarify?

**Comment by bharathcs** [comment]
Soz @DonnyS57 i turned it back into a draft cuz I'm still waiting on #20

**Review by mrmrinal — DISMISSED** [review]
LGTM! Changes in the ModelManager are reflected accurately.

**Review by Bluntsord — APPROVED** [review]

**Review by sheehui — APPROVED** [review]
looks great

**Pull request merged**
