### PR TITLE
Update info on sheehui in our AboutMe page

### PR DESCRIPTION
**Pull request by sheehui**
Add github link.
Add profile photo in .png as specified by 2103T website.
Add a pseudo portfolio in tp/team.

### CODE REVIEW

**Review by bharathcs — APPROVED** [review]
LGTM!

**Comment by bharathcs** [comment]
Btw do u wanna delete the placeholder stuff in `sheehui.md` and just keep adding to it every week or how?

**Comment by bharathcs** [comment]
And I feel maybe we can delete the project summary in the `sheehui.md`, no point everyone copy paste that paragraph right?

**Comment by sheehui** [comment]
> And I feel maybe we can delete the project summary in the `sheehui.md`, no point everyone copy paste that paragraph right?

I think we might want to leave it in as it seems to be each individual members' "portfolio page" so it will be a bit more complete to provide context as a whole so the content is more cohesive.

**Comment by sheehui** [comment]
> Btw do u wanna delete the placeholder stuff in `sheehui.md` and just keep adding to it every week or how?

Removed placeholders. We should keep johndoe.md tentatively for reference as we update portfolio page in the future.

**Pull request merged**
